---
# なぜかエラーが出るのでコメントアウトしとく
# - name: Instal required pip packages
#   pip:
#     name: requests

# - name: Create a Grafana Cloud stack
#   grafana.grafana.cloud_stack:
#     name: asterion
#     stack_slug: asterion
#     cloud_api_key: '{{ grafana_cloud_api_key }}'
#     org_slug: cp20
#     state: present

- name: Install Grafana gpg key
  get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /etc/apt/keyrings/grafana.asc
    mode: '0755'
    force: true

- name: Add Grafana apt repositories
  apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/grafana.asc] https://apt.grafana.com stable main
    state: present
  notify:
    - apt_update

- name: Install Grafana Alloy
  apt:
    name:
      - alloy
    state: present

- name: Ensure Grafana Alloy is enabled on boot
  systemd:
    daemon_reload: true
    name: alloy
    enabled: true

- name: Setup postgres_exporter
  shell: |
    sudo -u postgres psql -c "CREATE USER postgres_exporter WITH PASSWORD '$password';"
    sudo -u postgres psql -c "GRANT pg_monitor TO postgres_exporter;"
  environment:
    password: '{{ postgres_exporter_password }}'

- name: Install Grafana Alloy config
  template:
    src: config.alloy.j2
    dest: /etc/alloy/config.alloy
    owner: root
    mode: '0777'
  notify:
    - Restart Grafana Alloy
