---
- hosts: all
  gather_facts: true
  become: true

  roles:
    # - common
    # - docker
    # - postgresql
    # - python
    # - nodejs
    # - pnpm
    # - bun
    - grafana
    # - read-stack
    # - obsidian-livesync
    # - bot-yumi
    # - traq-ing
