---
read_stack_app_url: http://localhost:3000
read_stack_local_supabase_url: http://localhost:54321
read_stack_supabase_url: http://localhost:54321
read_stack_database_url: postgresql://postgres:postgres@127.0.0.1:54322/postgres
read_stack_supabase_anon_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0
# read_stack_supabase_github_client_id: in the vault
# read_stack_supabase_github_client_secret: in the vault
