---
- name: Uninstall old docker
  apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Install packages for installing docker
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present

- name: Add docker gpg key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0755'
    force: true

- name: Add docker apt repositorys
  apt_repository:
    repo: deb [arch={{ deb_architecture[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/{{ ansible_system | lower }}/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable
    state: present
  notify:
    - apt_update

- name: Install docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Ensure docker is enabled on boot
  systemd:
    daemon_reload: true
    name: docker
    enabled: true
